// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function valueFromEvent(e) {
  return e.target.value;
}

var component = ReasonReact.reducerComponent("Component 3");

function make(_children, parentChoice) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "mt3"
                        }, React.createElement("input", {
                              placeholder: "enter something",
                              onChange: (function (e) {
                                  return Curry._1(self[/* send */3], e.target.value);
                                })
                            }), React.createElement("ol", undefined, React.createElement("li", undefined, "One"), React.createElement("li", undefined, "Two"), React.createElement("li", undefined, "Three"), React.createElement("li", undefined, "Four"), React.createElement("li", undefined, parentChoice), React.createElement("li", undefined, self[/* state */1])));
            }),
          /* initialState */(function (param) {
              return "";
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (newText, _text) {
              return /* Update */Block.__(0, [newText]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.valueFromEvent = valueFromEvent;
exports.component = component;
exports.make = make;
/* component Not a pure module */
